import localFont from "next/font/local";
import "./globals.css";
import Link from "next/link";
import LoginBtn from "./LoginBtn";
import { getServerSession } from "next-auth";
import { authOptions } from "@/pages/api/auth/[...nextauth]";
import { LogOutBtn } from "./LogOutBtn";
import { Suspense } from "react";
import { cookies } from "next/headers";
import DarkMode from "./DarkMode";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  let session = await getServerSession(authOptions)
  let cookie = cookies().get('mode')
  return (
    <html lang="en">
       <body className={
        cookie != undefined && cookie.value == 'dark' 
          ? 'dark-mode'
          : ''
      }>
      <div className="navbar">
        <Link href="/" className="logo">Appleforum</Link>
        <Link href="/list">List</Link>
        <Link href="/write">Write</Link>
        <Link href="/register">회원가입</Link>
        {
            session
              ? <span>{session.user.name} {session.user.email}<LogOutBtn /> </span>
              : <LoginBtn />
          }
          <DarkMode />
      </div>
        {children}
      </body>
    </html>
  );
}
